name: Test Install Script

on:
  push:
    branches: [ main ]
    paths:
      - 'install-ubuntu.sh'
      - '.github/workflows/test-install.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'install-ubuntu.sh'
      - '.github/workflows/test-install.yml'

jobs:
  test-install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make install script executable
      run: chmod +x install-ubuntu.sh

    - name: Test install script (dry run)
      run: |
        # Test script syntax
        bash -n install-ubuntu.sh
        echo "✅ Script syntax is valid"

    - name: Run install script
      run: |
        # Run the actual installation
        ./install-ubuntu.sh

    - name: Verify Neovim installation
      run: |
        # Check if Neovim was installed
        if command -v nvim &> /dev/null; then
          echo "✅ Neovim installed successfully"
          nvim --version
        else
          echo "❌ Neovim not found"
          exit 1
        fi

    - name: Verify configuration
      run: |
        # Check if config directory exists
        if [ -d ~/.config/nvim ]; then
          echo "✅ Neovim configuration directory exists"
          ls -la ~/.config/nvim/
        else
          echo "❌ Neovim configuration not found"
          exit 1
        fi

        # Check for key config files
        for file in init.lua lua/chadrc.lua; do
          if [ -f ~/.config/nvim/$file ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file missing"
            exit 1
          fi
        done

    - name: Install clipboard provider
      run: |
        sudo apt update
        sudo apt install -y xclip

    - name: Test configuration syntax
      run: |
        # Test Lua syntax of configuration files
        find ~/.config/nvim/lua -name "*.lua" -exec lua -e "assert(loadfile('{}'))" \;
        echo "✅ Configuration syntax is valid"

    - name: Test basic Neovim functionality
      run: |
        # Test basic Neovim without loading custom config
        timeout 30s nvim --headless --clean -c 'lua print("Neovim works")' -c 'qa!'
        echo "✅ Neovim installation is functional"

    - name: Verify language servers
      run: |
        # Check if Go tools were installed
        if [ -d ~/go/bin ]; then
          echo "✅ Go tools directory exists"
          ls -la ~/go/bin/ || true
        fi

        # Check if Node.js tools were installed
        npm list -g --depth=0 | grep -E "(compose-language-service|bash-language-server)" || true